using System.Collections.Generic;
using UnityEngine;

namespace DinoBattle.Data
{
    /// <summary>
    /// One tier of the gauntlet: what stands on it, how many, and how much tougher than baseline.
    /// </summary>
    [System.Serializable]
    public class GauntletTierSpec
    {
        [Tooltip("Shown in the HUD. \"3층\", \"보스\".")]
        public string label = "";

        [Tooltip("Species that can appear on this tier. Filled round-robin so a mixed tier is mixed " +
                 "evenly rather than by luck.")]
        public List<CreatureDefinition> species = new();

        [Min(1)] public int count = 3;

        [Tooltip("Health multiplier applied at spawn. The main difficulty lever: it lengthens fights " +
                 "without making them unfair.")]
        [Min(0.1f)] public float healthScale = 1f;

        [Tooltip("Damage multiplier applied at spawn. Deliberately climbs far slower than health — " +
                 "damage scaling one-shots the player's creatures, which reads as unfair rather than " +
                 "hard.")]
        [Min(0.1f)] public float damageScale = 1f;

        [Tooltip("Last tier. Used for the HUD label and, later, for presentation.")]
        public bool isBoss;
    }

    /// <summary>
    /// The whole climb, as data.
    ///
    /// There is no armour scale here and that is deliberate. Damage is applied as
    /// <c>max(1, raw - armor)</c>, so armour is not a proportional knob: past the point where a tier's
    /// armour exceeds the attackers' damage, every hit in the game does exactly 1 and the difficulty
    /// curve becomes a wall. Health and damage scale predictably. Armour does not.
    ///
    /// Generated by <c>Dino Battle > 1. Generate Sample Content</c> rather than hand-authored, for
    /// the same reason the creature definitions are: it should be reproducible from a fresh clone and
    /// reviewable as a diff.
    /// </summary>
    [CreateAssetMenu(menuName = "Dino Battle/Gauntlet Ladder", fileName = "GauntletLadder")]
    public class GauntletLadder : ScriptableObject
    {
        [SerializeField] private List<GauntletTierSpec> tiers = new();


        public IReadOnlyList<GauntletTierSpec> Tiers => tiers;
        public int TierCount => tiers.Count;

        public GauntletTierSpec Tier(int index) =>
            index >= 0 && index < tiers.Count ? tiers[index] : null;

        /// <summary>Replace the whole ladder. Editor-only path, used by the content builder.</summary>
        public void SetTiers(List<GauntletTierSpec> newTiers)
        {
            tiers = newTiers;
        }
    }
}
